version: "3.8"

services:
  phx:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: score_dev
      PGPORT: 5432
      PGHOST: db
    command: mix phx.server
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 4000:4000

  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: